### ISSUE TITLE
Category content strategy

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#10]
- [x] review/update categories
- [x] incorporate ^ into guide/posts/help
- [ ] build category pages (show posts for ^ all on one page)
- [ ] link all category pills to category pages

**Comment by brianseek** [comment]
@lukefretwell here is the PR for this one: https://github.com/distributedgov/distributedgov.github.io/pull/30

I went a slightly different direction with this, I don't think Jekyll has a way to dynamically generate pages based on values within MD files (categories). I could have setup landing pages for each, but that would have required a lot of work every time a category is added.

What I did was setup a page at /topics that lists all topics with the pages that apply listed below each topic. This is similar to how the existing categories page works for categories on posts. The topics are linkable via the anchor link in the heading. Each topic on a service page is now clickable and linked to the anchored topic.

Let me know if this works or if you want to brainstorm other options.

**Comment by lukefretwell** [comment]
@brianseek this is great. Agree it's a lot of work and wish Jekyll made it easier to set up individual category pages. I'm going to move this to the backlog and meditate on whether this is what we should stick with or invest in specific category pages. Note that the ones we have are pretty much set in stone.

**Comment by lukefretwell** [comment]
@brianseek I created this a while ago: https://distributedgov.com/categories/

The news pills are linking to it from here: https://distributedgov.com/welcome-to-distributedgov/

Did you intend to start linking pills to the topics page you created?

Just let me know when I can delete the categories page.

**Comment by brianseek** [comment]
@lukefretwell I wasn't sure if you wanted that to be a separate thing for posts. I can integrate the two and remove the categories page.

**Comment by brianseek** [comment]
@lukefretwell I have updated posts to work in the topics page and changed the link for the pill in posts. https://github.com/distributedgov/distributedgov.github.io/pull/32

**Comment by brianseek** [comment]
@lukefretwell here is the re-vamp of topics https://github.com/distributedgov/distributedgov.github.io/pull/41

I also added a stubbed out topics block on the home page. It needs some icons added to the frontmatter of the topics to look good. It is currently commented out.
