### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#11]
I'd love for someone to review the code and share with me how I could approach this in a smarter way.

**Comment by JeffreyGarrett** [comment]
Start here https://handbook.civicactions.com/en/latest/05-engineering/git/#code-review
It helps to have a definition in your readme or another file how you approve code from others. 

Overly detailed but something to reference as what people might be looking for to get contributors. 
 https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md
