### ISSUE TITLE
Update 'edit this page' link

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#15]
Not sure this is linking to correct location. Discuss with OB.

**Comment by brianseek** [comment]
@lukefretwell These links look fine to me. Do you want to co-work on where you are seeing weird stuff with this?

**Comment by brianseek** [comment]
remove ability to commit directly to master. Force new branch

**Comment by brianseek** [comment]
@lukefretwell I have this setup with the same type of rules as handbook. Let me know if this is working for you.
