### ISSUE TITLE
Display multiple authors on training/coaching/consulting

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#18]
For some of the services, like training, we have multiple instructors (i.e. 'authors'). So it would be great to display each of these on the respective offering pages.

I tried to do this, but it's only showing the author name (like 'lukefretwell').

See here: https://distributedgov.com/training/recruiting-and-hiring-while-teleworking/

I started with this recommendation but can't display other elements like author image:

https://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll

Example code I'd like to display for each:

```
                    {% if page.author %}
                    {% assign author = site.data.people[page.author] %}
                    <div class="people people-jumbotron">
                        <a href="{{ author.url }}"><img src="{{ site.url }}/img/people/{{ author.image }}" alt="{{ author.name }}" title="{{ author.name }}"></a> <a href="{{ author.url }}">{{ author.name }}</a>, {{ author.bio_short }}
                    </div>
                    {% endif %}
                    {% if page.form %}
                    <div class="request">
                        <p><a class="btn btn-primary btn-lg" href="{{ page.form }}" role="button">Request {{ page.service | downcase }}</a> &nbsp; Questions? <a href="{{ site.url }}/contact">Contact us</a></p>
                    </div>
                    {% endif %}
```

**Comment by brianseek** [comment]
@lukefretwell this is ready to review in the PR for the consolidated people data ticket.
