### ISSUE TITLE
Switch distributedgov.org to .com domain

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#2]
- [x] Switch .org to .com
- [x] Set up https
- [x] redirect .org to .com

**Comment by lukefretwell** [comment]
@grugnog is this something you could do?

**Comment by grugnog** [comment]
DNS and redirects are done, and the domain is switched in https://github.com/distributedgov/distributedgov.github.io/settings
Waiting on cert provisioning by Github, then can enable "enforce SSL" on https://github.com/distributedgov/distributedgov.github.io/settings
