### ISSUE TITLE
Add conditional elements to sections on people page where nothing shows

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#22]
On the profile pages, would like to hide the sections where the person has no information.

Reference: https://distributedgov.com/people/melindaburgess/

Screenshot:

![FireShot Capture 247 - Melinda Burgess - DistributedGov - distributedgov com](https://user-images.githubusercontent.com/1569463/83197806-edc71b00-a0f2-11ea-9808-dd5b74781426.png)

**Comment by brianseek** [comment]
@lukefretwell there is a PR ready for this to review. I added a few comments in the layout along with my code refactor.
