### ISSUE TITLE
Add anchor links to headings

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#23]
Would love to be able to have anchor links auto-generated for headers.

Example: https://jekyllrb.com/docs/configuration/options/#global-configuration

**Comment by brianseek** [comment]
@lukefretwell do you want to also have that hover effect of showing the link icon with the copy to clipboard functionality? Or do you just want each header to have an ID for anchor linking?

**Comment by lukefretwell** [comment]
@brianseek you know I love me some hover effect of showing the link icon with the copy to clipboard functionality. 😆

**Comment by brianseek** [comment]
@lukefretwell this is ready to review at: https://github.com/distributedgov/distributedgov.github.io/pull/28

I ended up going with the include file for headings in layouts, which seems to work fine. For the guide where headings are set in MD, I added a little bit of JS to add the link icon.

**Comment by lukefretwell** [comment]
@brianseek is it possible to not show the anchor link image until hover and link the entire heading, similar to what Jekyll does on its site:

https://jekyllrb.com/docs/configuration/options/#global-configuration

**Comment by brianseek** [comment]
@lukefretwell it should already be doing that. You may need to do a hard refresh on your browser to pickup the css changes. Currently the functionality is identical to the Jekyll site. When you say link the entire header, do you mean that the whole header is a link to the anchored location and not just the link icon?

**Comment by lukefretwell** [comment]
@brianseek I see the CSS now. Yes, to the ☝️ question, whole header. I'm sure it'll look weird and I'll have to fix the CSS, but I think you should be able to click it from anywhere (and not just the icon) once the link icon shows.

**Comment by brianseek** [comment]
@lukefretwell Sounds good, I can do that. I'll make sure the css looks good too :)

**Comment by brianseek** [comment]
@lukefretwell I've got that updated here: https://github.com/distributedgov/distributedgov.github.io/pull/29/files
