### ISSUE TITLE
https://distributedgov.com/services/ throws 404

### ISSUE THREAD

**Issue by joduinn** [distributedgov/distributedgov.github.io#39]
On distributedgov.com, clicking on "services" will now get you a 404-page-not-found. This used to work. Using https://distributedgov.com/services fails the same way.

Also, on the 404 page, I notice a weird layout problem for the "powered by CivicActions" text at the top. Not sure if this is related to same template changes or should be in separate ticket.  
Good - on home page: ![Screen Shot 2020-06-11 at 13 09 50](https://user-images.githubusercontent.com/714805/84434612-38fa2700-abe5-11ea-8c83-a6428eb9c7d4.png)
Bad - on 404 page: ![Screen Shot 2020-06-11 at 13 09 43](https://user-images.githubusercontent.com/714805/84434624-3e577180-abe5-11ea-8b7a-8336b4e68bf1.png)

**Comment by brianseek** [comment]
@joduinn the path part is fixed now, will look at the weird 404 layout next

**Comment by lukefretwell** [comment]
@brianseek note I cleaned up the 404 page: https://distributedgov.com/404
