### ISSUE TITLE
add syntax checker to PRs for guide (and for website)

### ISSUE THREAD

**Issue by joduinn** [distributedgov/distributedgov.github.io#48]
From Trello
From slack:
grugnog(opens in new tab) 7:00 PM
@John O'Duinn We have a Gitlab.com repo configures to test Github PRs - this runs the CI checks configured in https://github.com/CivicActions/handbook/blob/master/.gitlab-ci.yml - setting this up on another repo should be possible, no special creds needed (we use the free plan and test runners). For the most part I think you would just need to copy all the non-markdown files from https://github.com/CivicActions/handbook to the other repo and then add it in Gitlab.
GitLabGitLab
CivicActions / handbook(opens in new tab)
The home of policies and guidelines that make up CivicActions
.gitlab-ci.yml(opens in new tab)
https://github.com/CivicActions/handbook|CivicActions/handbookCivicActions/handbook | Added by GitHub(opens in new tab)
CivicActions/handbook
Website
https://handbook.civicactions.com/en/latest/README/
Stars
4
https://github.com/CivicActions/handbook|CivicActions/handbookCivicActions/handbook | Oct 3rd, 2016 | Added by GitHub(opens in new tab)
eyes

**Comment by lukefretwell** [comment]
@joduinn is this something you and I can co-work on or do with need @grugnog's 🧠 ?

**Comment by lukefretwell** [comment]
@joduinn see previous questions. Closing this but feel free to re-open if it's a priority.
