### ISSUE TITLE
Unify card widths

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#67]
Would like to figure out how to make the card widths uniform regardless of how many there are.

Examples:

* 4 here: https://distributedgov.com/training
* 2 here: https://distributedgov.com/coaching

Ideally they would have same width and max at three across a column.

**Comment by brianseek** [comment]
@lukefretwell lemme know if this works for you. PR: https://github.com/distributedgov/distributedgov.github.io/pull/75
