### ISSUE TITLE
Add ability to add freeform text to services fields

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#68]
The pages are breaking when adding free form text to these services fields:

* `followup`
* `prerequisites`

Can we enable both of these to have paragraph, list and linking functionality?

Example:

```
prerequisites:
  - [Effective Telework in Distributed Government Teams](/training/effective-telework-in-distributed-government-teams)
  - [Managing Teleworkers in Government](training/managing-teleworkers-in-government)

```

**Comment by brianseek** [comment]
@lukefretwell I added a loop in prereqs in this PR: https://github.com/distributedgov/distributedgov.github.io/pull/70

I wasn't sure if you wanted those to print as bullet points like other sections do. As it is, it will just put each on a line of its own. If you want to add links like your example you will need to wrap them in quotes like this:
```
prerequisites:
  - "[Effective Telework in Distributed Government Teams](/training/effective-telework-in-distributed-government-teams)"
  - "[Managing Teleworkers in Government](training/managing-teleworkers-in-government)"
```
