### ISSUE TITLE
Move pages to _pages folder

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#8]
There are a number of pages in the root, and I'm wondering if it's best to move them to a _pages folder. What are best practices around this?

**Comment by lukefretwell** [comment]
Not sure if there's a need for this, but just wanted to discuss.

**Comment by brianseek** [comment]
@lukefretwell here is the PR for this: https://github.com/distributedgov/distributedgov.github.io/pull/37
I ended up refactoring the permalink stuff in config also.
