### ISSUE TITLE
Fix page titles

### ISSUE THREAD

**Issue by grugnog** [distributedgov/distributedgov.github.io#81]
The page titles include a comment, which is showing up (at least in Firefox and Chrome):
`<title>Title text<!--DistributedGov--></title>`

So on the home page I see: `Distributed Government - Distributed Government<!--DistributedGov-->`

I think we should remove the `<!--DistributedGov-->` part.

**Comment by lukefretwell** [comment]
@grugnog thank you for the find. This should be fixed.

**Comment by grugnog** [comment]
Confirming that fixed it!
