### ISSUE TITLE
Clean _layouts

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#9]
Several of these could probably be merged.

- [ ] merge where appropriate
- [ ] merge training/coaching/consulting layout?
- [ ] update reference layouts/files that use removed ones

**Comment by lukefretwell** [comment]
@brianseek I'm thinking it's a good idea to just merge these layouts:

* https://github.com/distributedgov/distributedgov.github.io/blob/master/_layouts/coaching.html
* https://github.com/distributedgov/distributedgov.github.io/blob/master/_layouts/consulting.html
* https://github.com/distributedgov/distributedgov.github.io/blob/master/_layouts/training.html

**Comment by brianseek** [comment]
@lukefretwell this one is ready to check out at https://github.com/distributedgov/distributedgov.github.io/pull/26
